import { Header, MobileActions, Testimonials } from "./components";
import { projects, services } from "./content";

export default function Home() {
  return <><Header /><main id="home">
    <section className="hero section-pad" aria-labelledby="hero-title">
      <div className="hero-copy"><p className="eyebrow"><span /> Trusted electrical services</p><h1 id="hero-title">Powering spaces.<br /><em>Built on trust.</em></h1><p className="hero-intro">Dependable electrical work for homes and businesses—delivered safely, explained clearly, and finished with care.</p><div className="hero-actions"><a className="button primary" href="mailto:hello@wrightsparks.co.uk?subject=Quote%20request">Get a free quote <span aria-hidden="true">↗</span></a><a className="text-link" href="#services">Explore services <span aria-hidden="true">↓</span></a></div><div className="trust-row"><span>✓ Fully qualified</span><span>✓ Residential & commercial</span><span>✓ Clear communication</span></div></div>
      <div className="hero-visual" aria-label="Abstract electrical circuit illustration"><div className="orb"><span className="bolt">ϟ</span></div><span className="circuit one"/><span className="circuit two"/><div className="availability"><i /> Available for new projects</div></div>
    </section>

    <section className="services section-pad" id="services" aria-labelledby="services-title"><div className="section-heading"><div><p className="eyebrow"><span /> What we do</p><h2 id="services-title">Electrical expertise,<br /><em>without the jargon.</em></h2></div><p>From a single fault to a full installation, we bring the same care, clarity and attention to every job.</p></div><div className="service-grid">{services.map(service => <article className="service-card" key={service.number}><span className="service-number">{service.number}</span><div className="service-icon" aria-hidden="true">{service.number === "01" ? "⌁" : service.number === "02" ? "✓" : "ϟ"}</div><h3>{service.title}</h3><p>{service.description}</p><small>{service.detail}</small></article>)}</div></section>

    <section className="work section-pad" id="work" aria-labelledby="work-title"><div className="section-heading light"><div><p className="eyebrow"><span /> Selected work</p><h2 id="work-title">Made safe.<br /><em>Made to last.</em></h2></div><p>A snapshot of the spaces and systems we help bring to life.</p></div><div className="project-grid">{projects.map((project, i) => <article className={`project project-${i + 1} ${project.tone}`} key={project.title}><div className="project-art"><span className="project-line"/><span className="project-glow"/></div><div><p>{project.category}</p><h3>{project.title}</h3></div></article>)}</div></section>

    <section className="about section-pad" id="about"><div className="about-copy"><p className="eyebrow"><span /> Why Wright Sparks</p><h2>Good work starts with<br /><em>doing things properly.</em></h2><p>We believe electrical work should feel straightforward. That means turning up prepared, respecting your space, and making sure you understand the work before we leave.</p><dl><div><dt>Clear</dt><dd>Plain advice and transparent next steps</dd></div><div><dt>Careful</dt><dd>Safe, tidy work with attention to detail</dd></div><div><dt>Dependable</dt><dd>Communication you can count on</dd></div></dl></div><div className="about-panel"><span className="panel-bolt" aria-hidden="true">ϟ</span><p>For homes.<br />For businesses.<br /><strong>For peace of mind.</strong></p></div></section>

    <section className="testimonials section-pad" aria-labelledby="testimonial-title"><div className="section-heading"><div><p className="eyebrow"><span /> Client feedback</p><h2 id="testimonial-title">Trusted where<br /><em>it matters most.</em></h2></div></div><Testimonials /></section>

    <section className="contact section-pad" id="contact" aria-labelledby="contact-title"><p className="eyebrow"><span /> Start a conversation</p><h2 id="contact-title">Have an electrical<br />project in mind?</h2><p>Tell us what you need. We’ll come back to you with a clear, no-obligation next step.</p><div className="contact-actions"><a className="button white" href="mailto:hello@wrightsparks.co.uk?subject=Quote%20request">Request a free quote <span aria-hidden="true">↗</span></a><a href="tel:+440000000000">Prefer to talk? Call us <span aria-hidden="true">→</span></a></div></section>
  </main><footer className="footer"><a className="wordmark inverse" href="#home"><span>WRIGHT</span><strong>SPARKS</strong></a><p>Professional electrical services for homes and businesses.</p><div><a href="#services">Services</a><a href="#work">Our work</a><a href="#about">About</a><a href="#contact">Contact</a></div><small>© {new Date().getFullYear()} Wright Sparks. All rights reserved.</small></footer><MobileActions /></>;
}
